service: emailsystem

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1
  stage: dev
  environment:
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline
